// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	IsVerified        *bool  `json:"is_Verified"`
	BankName          string `json:"bank_name"`
	BankCode          string `json:"bank_code"`
	BankAccountNumber string `json:"bank_account_number"`
}

type UserInput struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	IsVerified        *bool  `json:"is_Verified"`
	BankName          string `json:"bank_name"`
	BankCode          string `json:"bank_code"`
	BankAccountNumber string `json:"bank_account_number"`
}
